### PR TITLE
Add Reverse Each

### PR DESCRIPTION
**Pull request by rwtsoftware**
The main purpose of the change was to be able to parse the mail log in reverse.

I refactored certain functionality outside of the lock so that it could be resued within another lock
This refactor could probably be taken further but I have yet to do so at this time

### CODE REVIEW

**Comment by meh** [comment]
Do you want to refactor first or want me to merge first and then make another pull when you have time?

I'm fine with either.

**Comment by rwtsoftware** [comment]
If you're ok with the pattern *_no_lock I'll go ahead and refactored the rest of it in a separate commit. I'll probably also go ahead and make them private

**Comment by meh** [comment]
I'm fine with that pattern.

**Comment by rwtsoftware** [comment]
Code Updated.
Let me know if there is anything else I can do.

**Comment by meh** [comment]
Looks fine, thanks!

**Pull request merged**
